#!/bin/bash

echo "🔗 CONNECT TO EXISTING GITHUB REPOSITORY"
echo "======================================="

echo ""
echo "📋 To deploy FAQ page to https://www.drop-dollar.com/faq/"
echo ""

echo "🔍 Step 1: Find Your GitHub Repository"
echo "======================================"
echo "Do you already have a GitHub repository for drop-dollar?"
echo ""
echo "If YES:"
echo "1. Go to https://github.com/YOUR_USERNAME/drop-dollar"
echo "2. Copy the repository URL"
echo "3. Run: git remote add origin [YOUR_REPO_URL]"
echo ""
echo "If NO:"
echo "1. Go to https://github.com/new"
echo "2. Repository name: drop-dollar"
echo "3. Make it PUBLIC"
echo "4. DON'T initialize with README"
echo "5. Click 'Create repository'"
echo "6. Copy the repository URL"
echo ""

echo "🔧 Step 2: Connect and Push"
echo "=========================="
echo "Once you have the repository URL, run:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/drop-dollar.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""

echo "🚀 Step 3: Deploy to Vercel"
echo "=========================="
echo "1. Go to https://vercel.com/dashboard"
echo "2. Find your 'drop-dollar' project"
echo "3. Click 'Settings' → 'Git'"
echo "4. Connect to your GitHub repository"
echo "5. Click 'Redeploy'"
echo ""

echo "🎯 Result: FAQ Page Live!"
echo "========================"
echo "After deployment:"
echo "https://www.drop-dollar.com/faq/"
echo ""
echo "✅ 23 FAQ questions with answers"
echo "✅ Mobile-optimized design"
echo "✅ Search and filter functionality"
echo "✅ Contact support section"
echo ""

echo "❓ Need Help?"
echo "============="
echo "If you need help finding your GitHub repository or username,"
echo "let me know and I can help you locate it!"
