#!/bin/bash

echo "🚀 Drop Dollar Website - Deployment Setup"
echo "========================================"

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    echo "❌ Error: Please run this script from the project root directory"
    exit 1
fi

echo "📋 Current Status:"
echo "================="
echo "✅ Git repository initialized"
echo "✅ All files committed locally"
echo "✅ FAQ page created with 23 questions"
echo "✅ Mobile-optimized pages ready"
echo "❌ NOT YET DEPLOYED (that's why you can't see the FAQ!)"

echo ""
echo "🎯 To Deploy Your FAQ Page and All Changes:"
echo "=========================================="
echo ""
echo "1. Create GitHub Repository:"
echo "   • Go to https://github.com/new"
echo "   • Repository name: drop-dollar-website"
echo "   • Make it public"
echo "   • Don't initialize with README"
echo "   • Click 'Create repository'"
echo ""
echo "2. Connect and Push to GitHub:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/drop-dollar-website.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Deploy to Vercel:"
echo "   • Go to https://vercel.com"
echo "   • Sign in with GitHub"
echo "   • Click 'New Project'"
echo "   • Import your drop-dollar-website repository"
echo "   • Click 'Deploy'"
echo ""
echo "4. Add Environment Variables in Vercel:"
echo "   • Go to Project Settings > Environment Variables"
echo "   • Add STRIPE_SECRET_KEY, SUPABASE_URL, etc."
echo ""

echo "📱 After Deployment, You'll See:"
echo "================================"
echo "✅ FAQ Page: https://your-site.vercel.app/faq"
echo "   • 23 comprehensive FAQ questions"
echo "   • Search and filter functionality"
echo "   • Mobile-optimized design"
echo ""
echo "✅ Mobile Tournaments: https://your-site.vercel.app/tournaments"
echo "   • Fixed mobile layout"
echo "   • Touch-friendly interface"
echo "   • Responsive design"
echo ""
echo "✅ All Other Pages:"
echo "   • Token Purchase: /token-purchase"
echo "   • Sign In/Up: /signin, /signup"
echo "   • Navigation: /navigation"
echo "   • Mobile Test: /mobile-test"
echo ""

echo "🔧 Quick Commands:"
echo "=================="
echo "# Add GitHub remote (replace YOUR_USERNAME):"
echo "git remote add origin https://github.com/YOUR_USERNAME/drop-dollar-website.git"
echo ""
echo "# Push to GitHub:"
echo "git branch -M main"
echo "git push -u origin main"
echo ""

echo "📋 FAQ Page Content Preview:"
echo "============================"
echo "The FAQ page includes 23 questions covering:"
echo "• General Questions (What is Drop Dollar?, How to get started?)"
echo "• Trading Games (How do games work?, What crypto can I trade?)"
echo "• Drop Coin (What is Drop Coin?, How to buy tokens?)"
echo "• Tournaments (How do tournaments work?, What are prizes?)"
echo "• Account & Security (How to create account?, Is data secure?)"
echo "• Support (Forgot password?, Contact support?)"
echo "• Mobile & App (Is there mobile app?, Can I use on phone?)"
echo "• Payments (What payment methods?, Are there fees?)"
echo ""

echo "✅ READY TO DEPLOY!"
echo "=================="
echo "Your FAQ page and all mobile optimizations are ready."
echo "Follow the steps above to get them live on the web!"
echo ""
