#!/bin/bash

echo "🔧 Drop Dollar Payment System Setup"
echo "=================================="

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    echo "❌ Error: Please run this script from the project root directory"
    exit 1
fi

echo "📦 Installing dependencies..."
npm install

echo ""
echo "🔑 Environment Variables Setup"
echo "=============================="
echo "Please set up your environment variables:"
echo ""
echo "1. Copy the environment template:"
echo "   cp vercel-env-setup.txt .env.local"
echo ""
echo "2. Edit .env.local with your actual values:"
echo "   - Supabase URL and keys (already provided)"
echo "   - Stripe keys (already provided)"
echo "   - Drop Coin contract address"
echo "   - Webhook secrets"
echo ""
echo "3. For Vercel deployment:"
echo "   - Go to Vercel dashboard"
echo "   - Add environment variables from vercel-env-setup.txt"
echo "   - Redeploy your project"
echo ""

echo "🗄️  Database Setup"
echo "=================="
echo "The Supabase database schema is already set up."
echo "Make sure the 'payment_transactions' table exists with these columns:"
echo "  - id (text, primary key)"
echo "  - payment_method (text)"
echo "  - amount_usd (real)"
echo "  - token_amount (integer)"
echo "  - status (text)"
echo "  - customer_email (text)"
echo "  - customer_address (text)"
echo "  - payment_data (jsonb)"
echo "  - created_at (timestamp)"
echo "  - completed_at (timestamp)"
echo "  - transaction_hash (text)"
echo ""

echo "💳 Stripe Webhook Setup"
echo "======================="
echo "1. Go to Stripe Dashboard → Webhooks"
echo "2. Add endpoint: https://your-domain.com/api/webhooks/stripe"
echo "3. Select events: payment_intent.succeeded, payment_intent.payment_failed"
echo "4. Copy the webhook secret to STRIPE_WEBHOOK_SECRET"
echo ""

echo "🚀 Testing the Setup"
echo "==================="
echo "1. Start the development server:"
echo "   npm run dev"
echo ""
echo "2. Test payment creation:"
echo "   curl -X POST http://localhost:3000/api/create_payment \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"payment_method\":\"card\",\"token_amount\":100,\"customer_email\":\"test@example.com\"}'"
echo ""

echo "✅ Setup complete!"
echo "=================="
echo "Your payment system is now configured with:"
echo "  ✅ Supabase database integration"
echo "  ✅ Stripe payment processing"
echo "  ✅ Multiple payment methods (Card, Apple Pay, ETH, Bitcoin)"
echo "  ✅ Webhook handling for payment confirmations"
echo "  ✅ Error handling and validation"
echo ""
echo "Next steps:"
echo "  1. Deploy to Vercel with environment variables"
echo "  2. Set up Stripe webhooks"
echo "  3. Test the complete payment flow"
echo "  4. Deploy your Drop Coin smart contract"
echo ""
