#!/bin/bash

# 🚀 DropDollar Supabase Setup Script
# This script helps you create the .env.local file with your Supabase credentials

echo "🚀 DropDollar Supabase Setup"
echo "=============================="
echo ""

# Check if .env.local already exists
if [ -f ".env.local" ]; then
    echo "⚠️  .env.local file already exists!"
    echo "Do you want to overwrite it? (y/N)"
    read -r response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

echo "Please provide your Supabase credentials:"
echo ""

# Get Supabase URL
echo "📍 Enter your Supabase Project URL:"
echo "   (Found in Supabase Dashboard → Settings → API)"
echo "   Example: https://abcdefghijklmnop.supabase.co"
read -r SUPABASE_URL

# Get Anon Key
echo ""
echo "🔑 Enter your Supabase Anon Key:"
echo "   (Found in Supabase Dashboard → Settings → API)"
echo "   Example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
read -r ANON_KEY

# Get Service Role Key
echo ""
echo "🔐 Enter your Supabase Service Role Key:"
echo "   (Found in Supabase Dashboard → Settings → API)"
echo "   Example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
read -r SERVICE_ROLE_KEY

# Create .env.local file
cat > .env.local << EOF
# ========================================
# DROPDOLLAR ENVIRONMENT VARIABLES
# ========================================
# Generated by setup script on $(date)

# ========================================
# SUPABASE CONFIGURATION (REQUIRED FOR LOGIN/REGISTRATION)
# ========================================
NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY

# ========================================
# SITE CONFIGURATION
# ========================================
NEXT_PUBLIC_SITE_URL=https://drop-dollar.com
NEXT_PUBLIC_APP_NAME=DropDollar
NEXT_PUBLIC_APP_DESCRIPTION=Skill-based gaming marketplace

# ========================================
# DEVELOPMENT SETTINGS
# ========================================
NODE_ENV=production
NEXT_PUBLIC_DEBUG_MODE=false
EOF

echo ""
echo "✅ .env.local file created successfully!"
echo ""
echo "🔄 Next steps:"
echo "1. Run the database schema in Supabase SQL Editor"
echo "2. Restart your development server: npm run dev"
echo "3. Test registration and login functionality"
echo ""
echo "📖 For detailed instructions, see: COMPLETE_SUPABASE_SETUP.md"
echo ""
echo "🎉 Your DropDollar authentication system is ready!"
