import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

const supabase = createClient(supabaseUrl, supabaseKey);

export interface UserProfile {
  id: string;
  username: string;
  firstName: string;
  lastName: string;
  email: string;
  tokens: number; // Legacy - kept for backward compatibility
  purchased_tokens: number; // Non-cashable tokens (purchased or admin-granted)
  won_tokens: number; // Cashable tokens (won from games)
  balance: number;
  totalSpent: number;
  totalEarned: number;
  gamesPlayed: number;
  gamesWon: number;
  createdAt: string;
  updatedAt: string;
}

export interface TokenTransaction {
  id: string;
  userId: string;
  type: 'purchase' | 'game_entry' | 'game_win' | 'refund' | 'adjustment' | 'bonus';
  amount: number;
  balance_before: number;
  balance_after: number;
  description: string;
  stripePaymentIntentId?: string;
  relatedListingId?: string;
  relatedGameId?: string;
  metadata?: Record<string, any>;
  created_at: string;
}

export interface GameHistory {
  id: string;
  userId: string;
  gameType: string;
  gameName?: string;
  score: number;
  accuracy?: number;
  avgReactionTime?: number;
  gameDuration?: number;
  isPractice: boolean;
  isCompetition: boolean;
  listingId?: string;
  entryNumber?: number;
  placement?: number;
  prizeWon?: number;
  
  // Match information
  opponentName?: string;
  opponentScore?: number;
  matchId?: string;
  lotNumber?: string;
  
  metadata?: Record<string, any>;
  createdAt: string;
}

export interface PurchaseHistory {
  id: string;
  userId: string;
  purchaseType: string;
  amount: number;
  tokensPurchased?: number;
  tokensSpent?: number;
  stripePaymentIntentId?: string;
  stripeChargeId?: string;
  status: 'pending' | 'completed' | 'failed' | 'refunded';
  description?: string;
  metadata?: Record<string, any>;
  createdAt: string;
}

export interface UserStatistics {
  userId: string;
  username: string;
  email: string;
  tokens: number;
  balance: number;
  totalSpent: number;
  totalEarned: number;
  gamesPlayed: number;
  gamesWon: number;
  actualGamesPlayed: number;
  actualGamesWon: number;
  averageScore: number;
  bestScore: number;
  totalTokensPurchased: number;
  totalTokensSpent: number;
  totalPurchases: number;
  totalPurchaseAmount: number;
  createdAt: string;
  lastLogin?: string;
}

export class UserService {
  /**
   * Get current user from localStorage
   */
  static getCurrentUser(): { id: string; username: string; firstName: string; lastName: string; email: string } | null {
    try {
      if (typeof window === 'undefined') return null;
      
      const storedUser = localStorage.getItem('user');
      const isLoggedIn = localStorage.getItem('isLoggedIn') === 'true';
      
      if (storedUser && isLoggedIn) {
        const userData = JSON.parse(storedUser);
        return {
          id: userData.id || userData.sessionId,
          username: userData.username || 'User',
          firstName: userData.firstName || userData.username || 'User',
          lastName: userData.lastName || '',
          email: userData.email || 'user@dropdollar.com'
        };
      }
      
      return null;
    } catch (error) {
      console.error('❌ [UserService] Error getting current user:', error);
      return null;
    }
  }

  /**
   * Get or create user profile with full data sync
   * Uses EMAIL as the lookup key (UUID is auto-generated by Supabase)
   */
  static async getOrCreateUser(userData: {
    id: string;
    username: string;
    firstName: string;
    lastName: string;
    email: string;
  }): Promise<UserProfile> {
    try {
      console.log('🔍 [UserService] Fetching/Creating user by email:', userData.email);
      
      // First, try to get existing user BY EMAIL (not by ID)
      const { data: existingUser, error: fetchError } = await supabase
        .from('users')
        .select('*')
        .eq('email', userData.email)
        .single();

      if (existingUser && !fetchError) {
        console.log('✅ [UserService] Existing user found:', existingUser.id);
        console.log('💰 [UserService] Current tokens:', existingUser.tokens);
        console.log('💵 [UserService] Current balance:', existingUser.balance);
        
        // Update last login
        await supabase
          .from('users')
          .update({ last_login: new Date().toISOString() })
          .eq('id', existingUser.id);
        
        // Update localStorage with the real UUID from Supabase
        if (typeof window !== 'undefined') {
          const storedUser = localStorage.getItem('user');
          if (storedUser) {
            const parsedUser = JSON.parse(storedUser);
            parsedUser.id = existingUser.id; // Update to UUID
            localStorage.setItem('user', JSON.stringify(parsedUser));
            console.log('🔄 [UserService] Updated localStorage with UUID:', existingUser.id);
          }
        }
        
        return {
          id: existingUser.id,
          username: existingUser.username,
          firstName: existingUser.first_name || '',
          lastName: existingUser.last_name || '',
          email: existingUser.email,
          tokens: existingUser.tokens || 0,
          balance: existingUser.balance || 0,
          totalSpent: existingUser.total_spent || 0,
          totalEarned: existingUser.total_earned || 0,
          gamesPlayed: existingUser.games_played || 0,
          gamesWon: existingUser.games_won || 0,
          createdAt: existingUser.created_at,
          updatedAt: existingUser.updated_at || existingUser.created_at
        };
      }

      // Create new user if doesn't exist (let Supabase generate UUID)
      console.log('📝 [UserService] Creating new user in Supabase (UUID will be auto-generated)...');
      const newUser = {
        // DON'T send 'id' - let Supabase generate it
        username: userData.username,
        first_name: userData.firstName,
        last_name: userData.lastName,
        email: userData.email,
        role: 'buyer',
        tokens: 0,
        balance: 0,
        total_spent: 0,
        total_earned: 0,
        games_played: 0,
        games_won: 0,
        is_active: true,
        last_login: new Date().toISOString(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      };

      const { data, error } = await supabase
        .from('users')
        .insert([newUser])
        .select()
        .single();

      if (error) {
        console.error('❌ [UserService] Error creating user:', error);
        // Return basic profile even if Supabase fails
        return {
          id: userData.id,
          username: userData.username,
          firstName: userData.firstName,
          lastName: userData.lastName,
          email: userData.email,
          tokens: 0,
          balance: 0,
          totalSpent: 0,
          totalEarned: 0,
          gamesPlayed: 0,
          gamesWon: 0,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString()
        };
      }

      console.log('✅ [UserService] User created successfully with UUID:', data.id);
      
      // Update localStorage with the real UUID from Supabase
      if (typeof window !== 'undefined') {
        const storedUser = localStorage.getItem('user');
        if (storedUser) {
          const parsedUser = JSON.parse(storedUser);
          parsedUser.id = data.id; // Update to UUID
          localStorage.setItem('user', JSON.stringify(parsedUser));
          console.log('🔄 [UserService] Updated localStorage with new UUID:', data.id);
        }
      }
      
      return {
        id: data.id,
        username: data.username,
        firstName: data.first_name || '',
        lastName: data.last_name || '',
        email: data.email,
        tokens: data.tokens || 0,
        purchased_tokens: data.purchased_tokens || 0,
        won_tokens: data.won_tokens || 0,
        balance: data.balance || 0,
        totalSpent: data.total_spent || 0,
        totalEarned: data.total_earned || 0,
        gamesPlayed: data.games_played || 0,
        gamesWon: data.games_won || 0,
        createdAt: data.created_at,
        updatedAt: data.updated_at
      };
    } catch (error) {
      console.error('❌ [UserService] Exception in getOrCreateUser:', error);
      // Return basic profile even if exception occurs
      return {
        id: userData.id,
        username: userData.username,
        firstName: userData.firstName,
        lastName: userData.lastName,
        email: userData.email,
        tokens: 0,
        balance: 0,
        totalSpent: 0,
        totalEarned: 0,
        gamesPlayed: 0,
        gamesWon: 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      };
    }
  }

  /**
   * Get user profile by ID with fresh data from Supabase
   */
  static async getUserProfile(userId: string): Promise<UserProfile | null> {
    try {
      // CRITICAL: Validate UUID format before database query
      const isValidUUID = (id: string) => {
        const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
        return uuidRegex.test(id);
      };
      
      if (!userId || !isValidUUID(userId)) {
        console.error('❌ [UserService] Invalid user ID format (not a UUID):', userId);
        console.log('🧹 This appears to be old corrupted data. User should log out and log in again.');
        return null;
      }
      
      console.log('🔍 [UserService] Fetching user profile for ID:', userId);
      const { data, error } = await supabase
        .from('users')
        .select('*')
        .eq('id', userId)
        .single();

      if (error) {
        console.error('❌ [UserService] Error fetching user profile:', error);
        return null;
      }

      if (!data) {
        console.log('⚠️ [UserService] User profile not found for ID:', userId);
        return null;
      }

      console.log('✅ [UserService] User profile fetched:', data.id);
      console.log('💰 [UserService] Current tokens:', data.tokens);
      console.log('💵 [UserService] Current balance:', data.balance);
      
      return {
        id: data.id,
        username: data.username,
        firstName: data.first_name || '',
        lastName: data.last_name || '',
        email: data.email,
        tokens: data.tokens || 0,
        purchased_tokens: data.purchased_tokens || 0,
        won_tokens: data.won_tokens || 0,
        balance: data.balance || 0,
        totalSpent: data.total_spent || 0,
        totalEarned: data.total_earned || 0,
        gamesPlayed: data.games_played || 0,
        gamesWon: data.games_won || 0,
        createdAt: data.created_at,
        updatedAt: data.updated_at || data.created_at
      };
    } catch (error) {
      console.error('❌ [UserService] Exception in getUserProfile:', error);
      return null;
    }
  }

  /**
   * Get user profile by EMAIL with fresh data from Supabase
   * This is the preferred method to ensure we get the correct user
   */
  static async getUserProfileByEmail(email: string): Promise<UserProfile | null> {
    try {
      const { data, error } = await supabase
        .from('users')
        .select('*')
        .eq('email', email)
        .single();

      if (error || !data) {
        console.error('Profile fetch error:', error);
        return null;
      }

      return {
        id: data.id,
        username: data.username,
        firstName: data.first_name || '',
        lastName: data.last_name || '',
        email: data.email,
        tokens: data.tokens || 0,
        purchased_tokens: data.purchased_tokens || 0,
        won_tokens: data.won_tokens || 0,
        balance: data.balance || 0,
        totalSpent: data.total_spent || 0,
        totalEarned: data.total_earned || 0,
        gamesPlayed: data.games_played || 0,
        gamesWon: data.games_won || 0,
        createdAt: data.created_at,
        updatedAt: data.updated_at || data.created_at
      };
    } catch (error) {
      console.error('Profile error:', error);
      return null;
    }
  }

  /**
   * Update user tokens in Supabase (legacy - updates tokens field)
   */
  static async updateUserTokens(userId: string, newTokenAmount: number): Promise<boolean> {
    try {
      console.log('💰 [UserService] Updating user tokens:', userId, 'New amount:', newTokenAmount);
      
      const { data, error } = await supabase
        .from('users')
        .update({ 
          tokens: newTokenAmount,
          updated_at: new Date().toISOString()
        })
        .eq('id', userId)
        .select();

      if (error) {
        console.error('❌ [UserService] Error updating user tokens:', error);
        return false;
      }

      console.log('✅ [UserService] User tokens updated successfully:', data);
      console.log('💰 [UserService] New token balance:', newTokenAmount);
      
      // Trigger cross-page synchronization events
      if (typeof window !== 'undefined') {
        // Update localStorage
        localStorage.setItem('tokenBalance', newTokenAmount.toString());
        
        // Dispatch custom event for other components
        const event = new CustomEvent('tokenUpdated', {
          detail: { userId, tokens: newTokenAmount }
        });
        window.dispatchEvent(event);
        
        console.log('🔄 [UserService] Token synchronization events triggered');
      }
      
      return true;
    } catch (error) {
      console.error('❌ [UserService] Exception in updateUserTokens:', error);
      return false;
    }
  }

  /**
   * Add purchased tokens to user's purchased_tokens wallet (play wallet)
   */
  static async addPurchasedTokens(userId: string, tokenAmount: number): Promise<boolean> {
    try {
      console.log('💰 [UserService] Adding purchased tokens:', userId, 'Amount:', tokenAmount);
      
      // First, get current purchased_tokens balance
      const currentProfile = await this.getUserProfile(userId);
      if (!currentProfile) {
        console.error('❌ [UserService] User profile not found');
        return false;
      }
      
      const currentPurchased = currentProfile.purchased_tokens || 0;
      const newPurchasedBalance = currentPurchased + tokenAmount;
      
      console.log(`💰 [UserService] Current purchased_tokens: ${currentPurchased}, Adding: ${tokenAmount}, New balance: ${newPurchasedBalance}`);
      
      // Update purchased_tokens field
      const { data, error } = await supabase
        .from('users')
        .update({ 
          purchased_tokens: newPurchasedBalance,
          updated_at: new Date().toISOString()
        })
        .eq('id', userId)
        .select();

      if (error) {
        console.error('❌ [UserService] Error adding purchased tokens:', error);
        return false;
      }

      console.log('✅ [UserService] Purchased tokens added successfully:', data);
      console.log('💰 [UserService] New purchased_tokens balance:', newPurchasedBalance);
      
      // Trigger cross-page synchronization events
      if (typeof window !== 'undefined') {
        // Update localStorage with total tokens
        const totalTokens = newPurchasedBalance + (currentProfile.won_tokens || 0);
        localStorage.setItem('tokenBalance', totalTokens.toString());
        
        // Dispatch custom event for other components
        const event = new CustomEvent('tokenUpdated', {
          detail: { userId, tokens: totalTokens, purchased_tokens: newPurchasedBalance }
        });
        window.dispatchEvent(event);
        
        console.log('🔄 [UserService] Token synchronization events triggered');
      }
      
      return true;
    } catch (error) {
      console.error('❌ [UserService] Exception in addPurchasedTokens:', error);
      return false;
    }
  }

  /**
   * Update user balance
   */
  static async updateUserBalance(userId: string, newBalance: number): Promise<boolean> {
    try {
      console.log('💵 [UserService] Updating user balance:', userId, 'New amount:', newBalance);
      
      const { data, error } = await supabase
        .from('users')
        .update({ 
          balance: newBalance,
          updated_at: new Date().toISOString()
        })
        .eq('id', userId)
        .select();

      if (error) {
        console.error('❌ [UserService] Error updating user balance:', error);
        return false;
      }

      console.log('✅ [UserService] User balance updated successfully:', data);
      console.log('💵 [UserService] New balance:', newBalance);
      return true;
    } catch (error) {
      console.error('❌ [UserService] Exception in updateUserBalance:', error);
      return false;
    }
  }

  /**
   * Add token transaction and update user tokens
   */
  static async addTokenTransaction(transaction: Omit<TokenTransaction, 'id' | 'created_at'>): Promise<boolean> {
    try {
      console.log('📝 [UserService] Adding token transaction:', transaction);
      console.log('📝 [UserService] User ID:', transaction.userId);
      console.log('📝 [UserService] Type:', transaction.type);
      console.log('📝 [UserService] Amount:', transaction.amount);
      console.log('📝 [UserService] Stripe Payment Intent ID:', transaction.stripePaymentIntentId);
      
      const insertData: any = {
        user_id: transaction.userId,
        type: transaction.type,
        amount: transaction.amount,
        description: transaction.description,
        metadata: transaction.metadata || {},
        created_at: new Date().toISOString()
      };
      
      // Add optional fields if they exist
      if (transaction.balance_before !== undefined) {
        insertData.balance_before = transaction.balance_before;
      }
      if (transaction.balance_after !== undefined) {
        insertData.balance_after = transaction.balance_after;
      }
      if (transaction.stripePaymentIntentId) {
        insertData.stripe_payment_intent_id = transaction.stripePaymentIntentId;
      }
      
      console.log('📝 [UserService] Insert data:', JSON.stringify(insertData, null, 2));
      
      // Insert transaction
      const { data, error } = await supabase
        .from('token_transactions')
        .insert([insertData])
        .select();

      if (error) {
        console.error('❌ [UserService] Error adding token transaction:', error);
        console.error('❌ [UserService] Error code:', error.code);
        console.error('❌ [UserService] Error message:', error.message);
        
        // If RLS error, try server-side API endpoint
        if (error.code === '42501' || error.message.includes('policy') || error.message.includes('RLS')) {
          console.error('❌ [UserService] RLS POLICY ERROR - Trying server-side API endpoint');
          
          try {
            // Call server-side API endpoint that uses service role
            const response = await fetch('/api/payments/save-transaction', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                userId: transaction.userId,
                type: transaction.type,
                amount: transaction.amount,
                balance_before: transaction.balance_before,
                balance_after: transaction.balance_after,
                description: transaction.description,
                stripePaymentIntentId: transaction.stripePaymentIntentId,
                metadata: transaction.metadata
              })
            });

            if (response.ok) {
              const result = await response.json();
              console.log('✅ [UserService] Transaction saved via API:', result.transactionId);
              return true;
            } else {
              const errorData = await response.json();
              console.error('❌ [UserService] API endpoint failed:', errorData);
              return false;
            }
          } catch (apiError: any) {
            console.error('❌ [UserService] API endpoint exception:', apiError);
            return false;
          }
        }
        
        return false;
      }

      if (!data || data.length === 0) {
        console.error('❌ [UserService] No data returned from insert');
        return false;
      }

      console.log('✅ [UserService] Token transaction added successfully:', data);
      console.log('✅ [UserService] Transaction ID:', data[0]?.id);
      
      // NOTE: Token balance is updated separately before this method is called
      // This ensures the exact balance we want, avoiding race conditions
      
      return true;
    } catch (error: any) {
      console.error('❌ [UserService] Exception in addTokenTransaction:', error);
      console.error('❌ [UserService] Exception message:', error.message);
      console.error('❌ [UserService] Exception stack:', error.stack);
      return false;
    }
  }

  /**
   * Get user token transactions
   */
  static async getUserTokenTransactions(userId: string): Promise<TokenTransaction[]> {
    try {
      console.log('📜 [UserService] Fetching token transactions for user:', userId);
      const { data, error } = await supabase
        .from('token_transactions')
        .select('*')
        .eq('user_id', userId)
        .order('created_at', { ascending: false });

      if (error) {
        console.error('❌ [UserService] Error fetching token transactions:', error);
        return [];
      }

      console.log('✅ [UserService] Token transactions fetched:', data?.length || 0);
      if (data) {
        console.log('📊 [UserService] Sample transaction:', data[0]);
      }
      
      return (data || []).map(tx => ({
        id: tx.id,
        userId: tx.user_id,
        type: tx.type,
        amount: tx.amount,
        balance_before: tx.balance_before,
        balance_after: tx.balance_after,
        description: tx.description || 'Transaction',
        stripePaymentIntentId: tx.stripe_payment_intent_id,
        relatedListingId: tx.related_listing_id,
        relatedGameId: tx.related_game_id,
        metadata: tx.metadata || {},
        created_at: tx.created_at
      }));
    } catch (error) {
      console.error('❌ [UserService] Exception in getUserTokenTransactions:', error);
      return [];
    }
  }

  /**
   * Save game history
   */
  static async saveGameHistory(gameData: Omit<GameHistory, 'id' | 'createdAt'>): Promise<boolean> {
    try {
      console.log('🎮 [UserService] Saving game history:', gameData);
      
      const { data, error } = await supabase
        .from('game_history')
        .insert([{
          user_id: gameData.userId,
          game_type: gameData.gameType,
          game_name: gameData.gameName,
          score: gameData.score,
          accuracy: gameData.accuracy,
          avg_reaction_time: gameData.avgReactionTime,
          reaction_time: gameData.avgReactionTime,
          game_duration: gameData.gameDuration,
          duration_seconds: gameData.gameDuration,
          is_practice: gameData.isPractice,
          is_competition: gameData.isCompetition,
          mode: gameData.isPractice ? 'practice' : 'competition',
          listing_id: gameData.listingId,
          entry_number: gameData.entryNumber,
          placement: gameData.placement,
          prize_won: gameData.prizeWon,
          tokens_wagered: 0,
          tokens_won: gameData.prizeWon || 0,
          result: 'completed',
          metadata: gameData.metadata,
          created_at: new Date().toISOString()
        }])
        .select();

      if (error) {
        console.error('❌ [UserService] Error saving game history:', error);
        return false;
      }

      console.log('✅ [UserService] Game history saved successfully:', data);
      
      // Update games played count
      const userProfile = await this.getUserProfile(gameData.userId);
      if (userProfile) {
        await supabase
          .from('users')
          .update({ 
            games_played: (userProfile.gamesPlayed || 0) + 1,
            games_won: gameData.placement === 1 ? (userProfile.gamesWon || 0) + 1 : userProfile.gamesWon,
            updated_at: new Date().toISOString()
          })
          .eq('id', gameData.userId);
      }
      
      return true;
    } catch (error) {
      console.error('❌ [UserService] Exception in saveGameHistory:', error);
      return false;
    }
  }

  /**
   * Get user game history with opponent information
   */
  static async getUserGameHistory(userId: string): Promise<GameHistory[]> {
    try {
      console.log('🎮 [UserService] Fetching game history for user:', userId);
      
      // First, get the basic game history
      const { data: gameData, error: gameError } = await supabase
        .from('game_history')
        .select('*')
        .eq('user_id', userId)
        .order('created_at', { ascending: false });

      if (gameError) {
        console.error('❌ [UserService] Error fetching game history:', gameError);
        return [];
      }

      console.log('✅ [UserService] Game history fetched:', gameData?.length || 0);
      
      if (!gameData || gameData.length === 0) {
        return [];
      }

      // Get match information for competition games
      const competitionGames = gameData.filter(game => game.mode === 'competition');
      const matchIds = competitionGames
        .map(game => game.metadata?.match_id)
        .filter(Boolean);

      let matchData: any[] = [];
      if (matchIds.length > 0) {
        const { data: matches, error: matchError } = await supabase
          .from('matches')
          .select('*')
          .in('id', matchIds);

        if (!matchError && matches) {
          matchData = matches;
          console.log('✅ [UserService] Match data fetched:', matches.length);
        }
      }

      // Combine game history with match information
      const enhancedGameHistory = gameData.map(game => {
        const match = matchData.find(m => m.id === game.metadata?.match_id);
        
        return {
          id: game.id,
          userId: game.user_id,
          gameType: game.game_type,
          gameName: game.game_type,
          score: game.score,
          accuracy: game.accuracy,
          avgReactionTime: game.reaction_time,
          gameDuration: game.duration_seconds,
          isPractice: game.mode === 'practice',
          isCompetition: game.mode === 'competition',
          listingId: game.metadata?.listing_id,
          entryNumber: game.metadata?.entry_number,
          placement: null,
          prizeWon: game.tokens_won || 0,
          
          // Match information
          opponentName: match ? 
            (match.player1_id === userId ? match.player2_name : match.player1_name) : 
            undefined,
          opponentScore: match ? 
            (match.player1_id === userId ? match.player2_score : match.player1_score) : 
            undefined,
          matchId: match?.id,
          lotNumber: match?.lot_number,
          
          metadata: game.metadata,
          createdAt: game.created_at
        };
      });

      console.log('✅ [UserService] Enhanced game history with opponent data:', enhancedGameHistory.length);
      
      // Debug: Check competition vs practice games
      const competitionGamesDebug = enhancedGameHistory.filter(g => g.isCompetition);
      const practiceGames = enhancedGameHistory.filter(g => g.isPractice);
      console.log('🏆 [UserService] Competition games:', competitionGamesDebug.length);
      console.log('⭐ [UserService] Practice games:', practiceGames.length);
      
      if (enhancedGameHistory.length > 0) {
        console.log('📊 [UserService] Sample enhanced game:', enhancedGameHistory[0]);
        console.log('📊 [UserService] Game modes:', enhancedGameHistory.map(g => ({ 
          game: g.gameType, 
          mode: g.isPractice ? 'practice' : g.isCompetition ? 'competition' : 'unknown',
          score: g.score
        })));
      }

      return enhancedGameHistory;
    } catch (error) {
      console.error('❌ [UserService] Exception in getUserGameHistory:', error);
      return [];
    }
  }

  /**
   * Save purchase history
   */
  static async savePurchaseHistory(purchaseData: Omit<PurchaseHistory, 'id' | 'createdAt'>): Promise<boolean> {
    try {
      console.log('💳 [UserService] Saving purchase history:', purchaseData);
      console.log('💳 [UserService] User ID:', purchaseData.userId);
      console.log('💳 [UserService] Purchase Type:', purchaseData.purchaseType);
      console.log('💳 [UserService] Amount:', purchaseData.amount);
      console.log('💳 [UserService] Tokens Purchased:', purchaseData.tokensPurchased);
      console.log('💳 [UserService] Stripe Payment Intent ID:', purchaseData.stripePaymentIntentId);
      
      const insertData: any = {
        user_id: purchaseData.userId,
        purchase_type: purchaseData.purchaseType || 'tokens',
        amount: purchaseData.amount,
        tokens_purchased: purchaseData.tokensPurchased || 0,
        status: purchaseData.status || 'completed',
        description: purchaseData.description || `Purchased ${purchaseData.tokensPurchased || 0} tokens`,
        metadata: purchaseData.metadata || {},
        created_at: new Date().toISOString()
      };
      
      // Add optional fields if they exist
      if (purchaseData.tokensSpent !== undefined) {
        insertData.tokens_spent = purchaseData.tokensSpent;
      }
      if (purchaseData.stripePaymentIntentId) {
        insertData.stripe_payment_intent_id = purchaseData.stripePaymentIntentId;
      }
      if (purchaseData.stripeChargeId) {
        insertData.stripe_charge_id = purchaseData.stripeChargeId;
      }
      
      console.log('💳 [UserService] Insert data:', JSON.stringify(insertData, null, 2));
      
      // Try with regular client first
      const { data, error } = await supabase
        .from('purchase_history')
        .insert([insertData])
        .select();

      if (error) {
        console.error('❌ [UserService] Error saving purchase history:', error);
        console.error('❌ [UserService] Error code:', error.code);
        console.error('❌ [UserService] Error message:', error.message);
        
        // If RLS error, try server-side API endpoint
        if (error.code === '42501' || error.message.includes('policy') || error.message.includes('RLS')) {
          console.error('❌ [UserService] RLS POLICY ERROR - Trying server-side API endpoint');
          console.error('❌ [UserService] User ID:', purchaseData.userId);
          
          try {
            // Call server-side API endpoint that uses service role
            const response = await fetch('/api/payments/save-purchase-history', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                userId: purchaseData.userId,
                purchaseType: purchaseData.purchaseType,
                amount: purchaseData.amount,
                tokensPurchased: purchaseData.tokensPurchased,
                tokensSpent: purchaseData.tokensSpent,
                stripePaymentIntentId: purchaseData.stripePaymentIntentId,
                stripeChargeId: purchaseData.stripeChargeId,
                status: purchaseData.status,
                description: purchaseData.description,
                metadata: purchaseData.metadata
              })
            });

            if (response.ok) {
              const result = await response.json();
              console.log('✅ [UserService] Purchase history saved via API:', result.purchaseId);
              return true;
            } else {
              const errorData = await response.json();
              console.error('❌ [UserService] API endpoint failed:', errorData);
              return false;
            }
          } catch (apiError: any) {
            console.error('❌ [UserService] API endpoint exception:', apiError);
            return false;
          }
        }
        
        return false;
      }

      if (!data || data.length === 0) {
        console.error('❌ [UserService] No data returned from insert');
        console.error('❌ [UserService] This may indicate RLS is blocking the insert silently');
        return false;
      }

      console.log('✅ [UserService] Purchase history saved successfully:', data);
      console.log('✅ [UserService] Saved purchase ID:', data[0]?.id);
      return true;
    } catch (error: any) {
      console.error('❌ [UserService] Exception in savePurchaseHistory:', error);
      console.error('❌ [UserService] Exception message:', error.message);
      console.error('❌ [UserService] Exception stack:', error.stack);
      return false;
    }
  }

  /**
   * Get user purchase history
   */
  static async getUserPurchaseHistory(userId: string, limit: number = 50, offset: number = 0): Promise<PurchaseHistory[]> {
    try {
      console.log('💳 [UserService] Fetching purchase history for user:', userId, 'Limit:', limit, 'Offset:', offset);
      
      // Use direct query (optimized function may not exist)
      const { data, error } = await supabase
        .from('purchase_history')
        .select('*')
        .eq('user_id', userId)
        .order('created_at', { ascending: false })
        .range(offset, offset + limit - 1);

      if (error) {
        console.error('❌ [UserService] Error fetching purchase history:', error);
        console.error('❌ [UserService] Error code:', error.code);
        console.error('❌ [UserService] Error message:', error.message);
        return [];
      }

      console.log('✅ [UserService] Purchase history fetched:', data?.length || 0);
      return (data || []).map(purchase => ({
        id: purchase.id,
        userId: purchase.user_id,
        purchaseType: purchase.purchase_type,
        amount: purchase.amount,
        tokensPurchased: purchase.tokens_purchased,
        tokensSpent: purchase.tokens_spent,
        stripePaymentIntentId: purchase.stripe_payment_intent_id,
        stripeChargeId: purchase.stripe_charge_id,
        status: purchase.status,
        description: purchase.description,
        metadata: purchase.metadata || {},
        createdAt: purchase.created_at
      }));
    } catch (error) {
      console.error('❌ [UserService] Exception in getUserPurchaseHistory:', error);
      return [];
    }
  }

  /**
   * Get user statistics (aggregated data from view)
   */
  static async getUserStatistics(userId: string): Promise<UserStatistics | null> {
    try {
      console.log('📊 [UserService] Fetching user statistics for:', userId);
      const { data, error } = await supabase
        .from('user_statistics')
        .select('*')
        .eq('user_id', userId)
        .single();

      if (error) {
        console.error('❌ [UserService] Error fetching user statistics:', error);
        return null;
      }

      console.log('✅ [UserService] User statistics fetched:', data);
      return {
        userId: data.user_id,
        username: data.username,
        email: data.email,
        tokens: data.tokens || 0,
        purchased_tokens: data.purchased_tokens || 0,
        won_tokens: data.won_tokens || 0,
        balance: data.balance || 0,
        totalSpent: data.total_spent || 0,
        totalEarned: data.total_earned || 0,
        gamesPlayed: data.games_played || 0,
        gamesWon: data.games_won || 0,
        actualGamesPlayed: data.actual_games_played || 0,
        actualGamesWon: data.actual_games_won || 0,
        averageScore: data.average_score || 0,
        bestScore: data.best_score || 0,
        totalTokensPurchased: data.total_tokens_purchased || 0,
        totalTokensSpent: data.total_tokens_spent || 0,
        totalPurchases: data.total_purchases || 0,
        totalPurchaseAmount: data.total_purchase_amount || 0,
        createdAt: data.created_at,
        lastLogin: data.last_login
      };
    } catch (error) {
      console.error('❌ [UserService] Exception in getUserStatistics:', error);
      return null;
    }
  }

  /**
   * Get user withdrawal requests
   */
  static async getUserWithdrawalRequests(userId: string): Promise<any[]> {
    try {
      console.log('💰 [UserService] Fetching withdrawal requests for user:', userId);
      // For now, return empty array - this feature can be implemented later
      return [];
    } catch (error) {
      console.error('❌ [UserService] Error fetching withdrawal requests:', error);
      return [];
    }
  }

  /**
   * Get user bank accounts
   */
  static async getUserBankAccounts(userId: string): Promise<any[]> {
    try {
      console.log('🏦 [UserService] Fetching bank accounts for user:', userId);
      // For now, return empty array - this feature can be implemented later
      return [];
    } catch (error) {
      console.error('❌ [UserService] Error fetching bank accounts:', error);
      return [];
    }
  }
}

export default UserService;
