'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import CleanNavigation from '@/components/navigation/CleanNavigation';

export default function HomePage() {
  const [scrollY, setScrollY] = useState(0);
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    setIsVisible(true);
    const handleScroll = () => setScrollY(window.scrollY);
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  // Generate Star Wars scrolling stars - Travel all the way up
  useEffect(() => {
    const starsContainer = document.getElementById('stars-container-home');
    if (!starsContainer) return;
    
    // Clear existing stars
    starsContainer.innerHTML = '';
    
    // Generate more stars for continuous effect
    const starCount = 150; // More stars for better coverage
    for (let i = 0; i < starCount; i++) {
      const star = document.createElement('div');
      const size = Math.random() < 0.6 ? 'small' : Math.random() < 0.9 ? 'medium' : 'large';
      const left = Math.random() * 100;
      const duration = 4 + Math.random() * 6; // 4-10 seconds for slower, more visible travel
      const delay = Math.random() * 3; // Longer delay range
      const xOffset = (Math.random() - 0.5) * 300; // More horizontal drift
      
      star.className = `star-wars-star ${size}`;
      star.style.setProperty('--star-left', `${left}%`);
      star.style.setProperty('--star-duration', `${duration}s`);
      star.style.setProperty('--star-x', `${xOffset}px`);
      star.style.animationDelay = `${delay}s`;
      
      starsContainer.appendChild(star);
    }
    
    // Continuously regenerate stars for infinite scroll
    const regenerateInterval = setInterval(() => {
      // Add a few new stars periodically
      for (let i = 0; i < 10; i++) {
        const star = document.createElement('div');
        const size = Math.random() < 0.6 ? 'small' : Math.random() < 0.9 ? 'medium' : 'large';
        const left = Math.random() * 100;
        const duration = 4 + Math.random() * 6;
        const delay = 0;
        const xOffset = (Math.random() - 0.5) * 300;
        
        star.className = `star-wars-star ${size}`;
        star.style.setProperty('--star-left', `${left}%`);
        star.style.setProperty('--star-duration', `${duration}s`);
        star.style.setProperty('--star-x', `${xOffset}px`);
        star.style.animationDelay = `${delay}s`;
        
        starsContainer.appendChild(star);
      }
    }, 2000); // Add new stars every 2 seconds
    
    // Cleanup
    return () => {
      clearInterval(regenerateInterval);
      if (starsContainer) {
        starsContainer.innerHTML = '';
      }
    };
  }, []);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-indigo-900 overflow-hidden relative">
      {/* Star Wars Scrolling Stars Background - Travel all the way up behind everything */}
      <div className="fixed inset-0 overflow-visible pointer-events-none" id="stars-container-home" style={{ zIndex: 0 }}>
        {/* Stars will be generated by useEffect */}
      </div>
      
      {/* Animated Purple Glow Background - Same style as games page */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none" style={{ zIndex: 0 }}>
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-purple-500/40 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute top-1/2 right-1/4 w-80 h-80 bg-purple-600/35 rounded-full blur-3xl animate-pulse" style={{ animationDelay: '1s' }}></div>
        <div className="absolute bottom-1/4 left-1/2 w-72 h-72 bg-indigo-500/40 rounded-full blur-3xl animate-pulse" style={{ animationDelay: '2s' }}></div>
        <div className="absolute top-1/3 right-1/3 w-64 h-64 bg-purple-400/30 rounded-full blur-3xl animate-pulse" style={{ animationDelay: '0.5s' }}></div>
        <div className="absolute bottom-1/3 left-1/6 w-88 h-88 bg-indigo-600/35 rounded-full blur-3xl animate-pulse" style={{ animationDelay: '1.5s' }}></div>
        <div className="absolute top-2/3 right-1/6 w-76 h-76 bg-purple-500/30 rounded-full blur-3xl animate-pulse" style={{ animationDelay: '2.5s' }}></div>
      </div>
      
      <CleanNavigation variant="gradient" currentPage="/" />

      {/* Hero Section with Parallax */}
      <section className="relative min-h-screen flex items-center justify-center overflow-hidden z-10">

        <div className={`relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center transition-all duration-1000 ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`}>
          {/* Main Title */}
          <h1 className="text-6xl md:text-8xl font-black mb-6 leading-tight">
            <span className="inline-block bg-gradient-to-r from-blue-400 via-purple-500 to-pink-500 bg-clip-text text-transparent animate-gradient">
              Welcome to
            </span>
            <br />
            <span className="inline-block bg-gradient-to-r from-yellow-400 via-orange-500 to-red-500 bg-clip-text text-transparent animate-gradient-reverse text-7xl md:text-9xl">
              DropDollar
            </span>
          </h1>

          {/* Subtitle */}
          <p className="text-xl md:text-3xl text-gray-200 mb-12 max-w-4xl mx-auto font-light leading-relaxed">
            Where Gaming Meets Opportunity
          </p>

          {/* Video Section */}
          <div className="mb-12 max-w-4xl mx-auto">
            <div className="relative rounded-2xl overflow-hidden shadow-2xl border-4 border-purple-500/50 hover:border-purple-400 transition-all duration-300 transform hover:scale-105">
              <div className="aspect-video bg-gradient-to-br from-gray-800 to-gray-900">
                <iframe
                  width="100%"
                  height="100%"
                  src="https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=0&mute=0&controls=1&rel=0"
                  title="DropDollar Introduction"
                  frameBorder="0"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                  allowFullScreen
                  className="w-full h-full"
                ></iframe>
              </div>
              <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent pointer-events-none"></div>
            </div>
          </div>

          {/* Practice Games Promo Section */}
          <div className="mb-16 max-w-5xl mx-auto">
            <div className="text-center mb-6">
              <h3 className="text-2xl md:text-3xl font-bold text-white mb-2">
                🎮 <span className="bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent">Practice Makes Perfect</span>
              </h3>
              <p className="text-gray-300 text-lg">Master 16 skill-based games before entering real competitions!</p>
            </div>
            
            {/* Gameplay Videos Grid */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {/* Laser Dodge */}
              <Link href="/games" className="group relative rounded-xl overflow-hidden shadow-xl border-2 border-cyan-500/30 hover:border-cyan-400 transition-all duration-300 transform hover:scale-105">
                <div className="aspect-video bg-gradient-to-br from-gray-800 to-gray-900">
                  <video
                    src="/laser-dodge-gameplay.mp4"
                    autoPlay
                    loop
                    muted
                    playsInline
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent pointer-events-none"></div>
                <div className="absolute bottom-0 left-0 right-0 p-3">
                  <div className="flex items-center justify-between">
                    <div>
                      <h4 className="text-white font-bold text-lg">⚡ Laser Dodge</h4>
                      <p className="text-cyan-300 text-xs">Dodge deadly lasers!</p>
                    </div>
                    <div className="bg-cyan-500/80 text-white text-xs px-2 py-1 rounded-full font-bold opacity-0 group-hover:opacity-100 transition-opacity">
                      PLAY →
                    </div>
                  </div>
                </div>
                {/* Live indicator */}
                <div className="absolute top-2 left-2 bg-red-500 text-white text-xs px-2 py-0.5 rounded-full font-bold animate-pulse flex items-center gap-1">
                  <span className="w-1.5 h-1.5 bg-white rounded-full"></span>
                  LIVE
                </div>
              </Link>

              {/* Blade Bounce */}
              <Link href="/games" className="group relative rounded-xl overflow-hidden shadow-xl border-2 border-orange-500/30 hover:border-orange-400 transition-all duration-300 transform hover:scale-105">
                <div className="aspect-video bg-gradient-to-br from-gray-800 to-gray-900">
                  <video
                    src="/mouseblade-gameplay.mp4"
                    autoPlay
                    loop
                    muted
                    playsInline
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent pointer-events-none"></div>
                <div className="absolute bottom-0 left-0 right-0 p-3">
                  <div className="flex items-center justify-between">
                    <div>
                      <h4 className="text-white font-bold text-lg">🗡️ Blade Bounce</h4>
                      <p className="text-orange-300 text-xs">Master the sword!</p>
                    </div>
                    <div className="bg-orange-500/80 text-white text-xs px-2 py-1 rounded-full font-bold opacity-0 group-hover:opacity-100 transition-opacity">
                      PLAY →
                    </div>
                  </div>
                </div>
                {/* Live indicator */}
                <div className="absolute top-2 left-2 bg-red-500 text-white text-xs px-2 py-0.5 rounded-full font-bold animate-pulse flex items-center gap-1">
                  <span className="w-1.5 h-1.5 bg-white rounded-full"></span>
                  LIVE
                </div>
              </Link>

              {/* Cash Stack */}
              <Link href="/games" className="group relative rounded-xl overflow-hidden shadow-xl border-2 border-yellow-500/30 hover:border-yellow-400 transition-all duration-300 transform hover:scale-105">
                <div className="aspect-video bg-gradient-to-br from-gray-800 to-gray-900">
                  <video
                    src="/cash-stack-gameplay.mp4"
                    autoPlay
                    loop
                    muted
                    playsInline
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent pointer-events-none"></div>
                <div className="absolute bottom-0 left-0 right-0 p-3">
                  <div className="flex items-center justify-between">
                    <div>
                      <h4 className="text-white font-bold text-lg">💰 Cash Stack</h4>
                      <p className="text-yellow-300 text-xs">Stack your fortune!</p>
                    </div>
                    <div className="bg-yellow-500/80 text-white text-xs px-2 py-1 rounded-full font-bold opacity-0 group-hover:opacity-100 transition-opacity">
                      PLAY →
                    </div>
                  </div>
                </div>
                {/* Live indicator */}
                <div className="absolute top-2 left-2 bg-red-500 text-white text-xs px-2 py-0.5 rounded-full font-bold animate-pulse flex items-center gap-1">
                  <span className="w-1.5 h-1.5 bg-white rounded-full"></span>
                  LIVE
                </div>
              </Link>
            </div>

            {/* View All Games Button */}
            <div className="text-center mt-6">
              <Link
                href="/games"
                className="inline-flex items-center gap-2 px-8 py-3 bg-gradient-to-r from-cyan-500 to-blue-600 text-white font-bold rounded-full hover:from-cyan-400 hover:to-blue-500 transition-all duration-300 transform hover:scale-105 shadow-lg hover:shadow-cyan-500/30"
              >
                🎮 View All 16 Games
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
                </svg>
              </Link>
            </div>
          </div>

          {/* CTA Buttons */}
          <div className="flex flex-col sm:flex-row gap-6 justify-center mb-20">
            <Link
              href="/auth/login"
              className="group relative px-12 py-5 bg-gradient-to-r from-blue-600 to-purple-600 text-white text-xl font-bold rounded-full hover:from-blue-700 hover:to-purple-700 transition-all duration-300 transform hover:scale-110 hover:shadow-2xl"
            >
              <span className="relative z-10">Get Started</span>
              <div className="absolute inset-0 bg-gradient-to-r from-blue-400 to-purple-400 rounded-full blur opacity-0 group-hover:opacity-75 transition-opacity duration-300"></div>
            </Link>
            <Link
              href="/games"
              className="group relative px-12 py-5 bg-gradient-to-r from-purple-600 to-pink-600 text-white text-xl font-bold rounded-full hover:from-purple-700 hover:to-pink-700 transition-all duration-300 transform hover:scale-110 hover:shadow-2xl"
            >
              <span className="relative z-10">Explore Games</span>
              <div className="absolute inset-0 bg-gradient-to-r from-purple-400 to-pink-400 rounded-full blur opacity-0 group-hover:opacity-75 transition-opacity duration-300"></div>
            </Link>
          </div>
        </div>

        {/* Scroll Indicator */}
        <div className="absolute bottom-10 left-1/2 transform -translate-x-1/2 animate-bounce">
          <svg className="w-6 h-6 text-white" fill="none" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M19 14l-7 7m0 0l-7-7m7 7V3"></path>
          </svg>
        </div>
      </section>

      {/* Features Section */}
      <section className="relative py-32 bg-black/30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-5xl md:text-6xl font-bold text-center mb-20">
            <span className="bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent">
              Why DropDollar?
            </span>
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {/* Feature 1 */}
            <div className="group relative bg-gradient-to-br from-blue-900/50 to-purple-900/50 backdrop-blur-xl p-8 rounded-3xl border border-blue-500/30 hover:border-blue-400 transition-all duration-500 transform hover:-translate-y-4 hover:shadow-2xl">
              <div className="text-6xl mb-6 transform group-hover:scale-110 transition-transform duration-300">🎮</div>
              <h3 className="text-2xl font-bold text-white mb-4">Exciting Games</h3>
              <p className="text-gray-300 leading-relaxed">
                Play skill-based games and compete for real prizes. Fast-paced action meets strategic gameplay.
              </p>
            </div>

            {/* Feature 2 */}
            <div className="group relative bg-gradient-to-br from-purple-900/50 to-pink-900/50 backdrop-blur-xl p-8 rounded-3xl border border-purple-500/30 hover:border-purple-400 transition-all duration-500 transform hover:-translate-y-4 hover:shadow-2xl">
              <div className="text-6xl mb-6 transform group-hover:scale-110 transition-transform duration-300">🔒</div>
              <h3 className="text-2xl font-bold text-white mb-4">Secure Platform</h3>
              <p className="text-gray-300 leading-relaxed">
                Bank-level security with Stripe payments. Your data and funds are always protected.
              </p>
            </div>

            {/* Feature 3 */}
            <div className="group relative bg-gradient-to-br from-pink-900/50 to-orange-900/50 backdrop-blur-xl p-8 rounded-3xl border border-pink-500/30 hover:border-pink-400 transition-all duration-500 transform hover:-translate-y-4 hover:shadow-2xl">
              <div className="text-6xl mb-6 transform group-hover:scale-110 transition-transform duration-300">⚡</div>
              <h3 className="text-2xl font-bold text-white mb-4">Instant Payouts</h3>
              <p className="text-gray-300 leading-relaxed">
                Win prizes and get paid instantly. Fast, secure transactions directly to your account.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="relative py-32">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-5xl md:text-6xl font-bold text-center mb-20">
            <span className="bg-gradient-to-r from-yellow-400 to-orange-500 bg-clip-text text-transparent">
              How It Works
            </span>
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            {/* Step 1 */}
            <div className="text-center group">
              <div className="w-24 h-24 mx-auto mb-6 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-4xl font-bold text-white shadow-2xl transform group-hover:scale-110 transition-transform duration-300">
                1
              </div>
              <h3 className="text-xl font-bold text-white mb-3">Sign Up</h3>
              <p className="text-gray-400">Create your free account in seconds</p>
            </div>

            {/* Step 2 */}
            <div className="text-center group">
              <div className="w-24 h-24 mx-auto mb-6 bg-gradient-to-br from-purple-500 to-pink-600 rounded-full flex items-center justify-center text-4xl font-bold text-white shadow-2xl transform group-hover:scale-110 transition-transform duration-300">
                2
              </div>
              <h3 className="text-xl font-bold text-white mb-3">Buy Tokens</h3>
              <p className="text-gray-400">Purchase tokens to enter games</p>
            </div>

            {/* Step 3 */}
            <div className="text-center group">
              <div className="w-24 h-24 mx-auto mb-6 bg-gradient-to-br from-pink-500 to-orange-600 rounded-full flex items-center justify-center text-4xl font-bold text-white shadow-2xl transform group-hover:scale-110 transition-transform duration-300">
                3
              </div>
              <h3 className="text-xl font-bold text-white mb-3">Play & Win</h3>
              <p className="text-gray-400">Compete and win amazing prizes</p>
            </div>

            {/* Step 4 */}
            <div className="text-center group">
              <div className="w-24 h-24 mx-auto mb-6 bg-gradient-to-br from-orange-500 to-red-600 rounded-full flex items-center justify-center text-4xl font-bold text-white shadow-2xl transform group-hover:scale-110 transition-transform duration-300">
                4
              </div>
              <h3 className="text-xl font-bold text-white mb-3">Get Paid</h3>
              <p className="text-gray-400">Receive your winnings instantly</p>
            </div>
          </div>
        </div>
      </section>

      {/* Other Apps from Drop Dollar Section */}
      <section className="relative py-24 bg-gradient-to-r from-green-900/60 to-yellow-900/60 border-t-4 border-yellow-400/30">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
              Other Apps from Drop Dollar
            </h2>
            <p className="text-xl text-gray-200 mb-8 max-w-3xl mx-auto">
              Explore our other innovative applications
            </p>
          </div>
          
          <Link
            href="/mog-me"
            className="block group relative max-w-4xl mx-auto px-8 py-10 bg-gradient-to-br from-green-700/90 to-green-800/90 rounded-3xl hover:from-green-600 hover:to-green-700 transition-all duration-300 transform hover:scale-[1.02] shadow-2xl border-4 border-yellow-400/60 hover:border-yellow-400 hover:shadow-yellow-400/30"
          >
            <div className="flex flex-col sm:flex-row items-center gap-6 sm:gap-8">
              {/* Mog Me Icon */}
              <div className="w-24 h-24 sm:w-28 sm:h-28 bg-gradient-to-br from-green-700 to-green-800 rounded-2xl flex items-center justify-center border-4 border-yellow-400/70 shadow-xl flex-shrink-0">
                <span className="text-6xl sm:text-7xl font-serif text-yellow-400 drop-shadow-[0_0_15px_rgba(250,204,21,0.9)]">M</span>
              </div>
              
              <div className="flex-1 text-center sm:text-left">
                <h3 className="text-3xl sm:text-4xl font-bold text-yellow-300 mb-3">Mog Me</h3>
                <p className="text-green-100 text-lg sm:text-xl mb-2">Your Ultimate Look Maxxing App</p>
                <p className="text-green-200 text-sm sm:text-base">
                  Transform your appearance and maximize your potential with cutting-edge tools and expert guidance
                </p>
              </div>
              
              <div className="text-yellow-400 text-3xl sm:text-4xl group-hover:translate-x-2 transition-transform flex-shrink-0">
                →
              </div>
            </div>
          </Link>
        </div>
      </section>

          {/* Final CTA Section */}
      <section className="relative py-32 bg-gradient-to-r from-blue-900/50 to-purple-900/50">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-5xl md:text-6xl font-bold text-white mb-8">
            Ready to Start Winning?
          </h2>
          <p className="text-xl text-gray-300 mb-12 max-w-3xl mx-auto">
            Join thousands of players competing for real prizes every day
          </p>
          <Link
            href="/auth/login"
            className="inline-block px-16 py-6 bg-gradient-to-r from-yellow-500 to-orange-600 text-white text-2xl font-bold rounded-full hover:from-yellow-600 hover:to-orange-700 transition-all duration-300 transform hover:scale-110 hover:shadow-2xl"
          >
            Join Now - It's Free!
          </Link>
        </div>
      </section>

      {/* Custom Animations */}
      <style jsx global>{`
        @keyframes blob {
          0%, 100% { transform: translate(0, 0) scale(1); }
          25% { transform: translate(20px, -50px) scale(1.1); }
          50% { transform: translate(-20px, 20px) scale(0.9); }
          75% { transform: translate(50px, 50px) scale(1.05); }
        }

        @keyframes gradient {
          0%, 100% { background-position: 0% 50%; }
          50% { background-position: 100% 50%; }
        }

        .animate-blob {
          animation: blob 7s infinite;
        }

        .animation-delay-2000 {
          animation-delay: 2s;
        }

        .animation-delay-4000 {
          animation-delay: 4s;
        }

        .animate-gradient {
          background-size: 200% 200%;
          animation: gradient 3s ease infinite;
        }

        .animate-gradient-reverse {
          background-size: 200% 200%;
          animation: gradient 3s ease infinite reverse;
        }
      `}</style>
    </div>
  );
}
