'use client';

import React from 'react';
import Link from 'next/link';
import CleanNavigation from '@/components/navigation/CleanNavigation';
import { FileText, ArrowLeft } from 'lucide-react';

const CONTACT_EMAIL = 'ryanfermoselle@outlook.com';
const APPLE_REPORT_URL = 'https://reportaproblem.apple.com';

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-green-900 via-green-800 to-yellow-900">
      <CleanNavigation variant="gradient" currentPage="/mog-me" />

      <section className="relative py-20 px-4 sm:px-6 lg:px-8 z-10">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center justify-center mb-8">
            <FileText className="w-12 h-12 text-yellow-400 mr-4" />
            <h1 className="text-4xl sm:text-5xl font-black text-center">
              <span className="bg-gradient-to-r from-yellow-300 via-yellow-400 to-yellow-500 bg-clip-text text-transparent">
                MogME AI - Terms of Service
              </span>
            </h1>
          </div>

          <p className="text-xl text-green-200 text-center mb-6">
            <strong>Last Updated: June 15, 2026</strong>
          </p>

          <div className="bg-yellow-400/20 backdrop-blur-xl p-6 rounded-2xl border-2 border-yellow-400/50 mb-8">
            <p className="text-green-100 text-lg font-semibold">
              <strong className="text-yellow-300">Agreement:</strong> By downloading, installing, or using MogME AI
              (&quot;the App&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the App.
            </p>
          </div>

          <div className="bg-green-800/40 backdrop-blur-xl p-10 rounded-3xl border-2 border-yellow-400/40 space-y-8 text-green-100">
            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">1. Acceptance of Terms</h2>
              <p className="mb-3">By accessing or using the App, you agree to:</p>
              <ul className="space-y-2 list-disc list-inside">
                <li>Comply with these Terms and all applicable laws.</li>
                <li>Be at least 18 years of age (or the age of majority in your jurisdiction).</li>
                <li>
                  Accept our{' '}
                  <Link href="/mog-me/privacy-policy" className="text-yellow-400 hover:underline">
                    Privacy Policy
                  </Link>{' '}
                  (incorporated by reference).
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">2. Description of Service</h2>
              <p className="mb-3">
                <strong>MogME AI provides:</strong>
              </p>
              <ul className="space-y-2 list-disc list-inside">
                <li>
                  <strong>Facial &amp; Body Analysis:</strong> On-device AI analysis of facial/physique features (PSL scoring)
                  using Apple&apos;s Vision Framework.
                </li>
                <li>
                  <strong>Fitness &amp; GPS Workout Tracking:</strong> Workout planning plus GPS-based tracking of pace,
                  distance, route, and elevation for cardio/walking workouts, with Apple Watch support and HealthKit integration.
                </li>
                <li>
                  <strong>Nutrition &amp; Diet Tracking:</strong> Meal logging, food image recognition, and personalized
                  calorie/macro targets (estimates only, not medical/dietetic advice).
                </li>
                <li>
                  <strong>Mental &amp; Physical Games:</strong> Cognitive training and AR-based physical games.
                </li>
                <li>
                  <strong>Leaderboards &amp; Public Username:</strong> Optional global leaderboards where a chosen public
                  handle and your scores are displayed to other users.
                </li>
                <li>
                  <strong>AI Companion &amp; AI Chat:</strong> AI Companion (&quot;Meet-Cute&quot;) and AI Rizz chat features
                  whose replies are generated by a third-party AI provider, for entertainment.
                </li>
                <li>
                  <strong>Social Sharing:</strong> Optionally share a generated image card of your results to other apps/social
                  media that you choose.
                </li>
                <li>
                  <strong>Mog-Off (Optional, 18+):</strong> An opt-in head-to-head competitive mode (Face, Cognition, AI Rizz).
                  In the Face round, your photo is analyzed on-device and only a numeric score and a deliberately distorted,
                  watermarked outline image are uploaded and shown to your opponent.
                </li>
                <li>
                  <strong>Premium Features:</strong> Advanced analysis, unlimited scans, detailed reports.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">3. Free vs. Premium Features</h2>
              <p>
                <strong>Free:</strong> basic PSL score, key metrics, camera/photo capture, limited history, basic fitness
                tracking.
              </p>
              <p className="mt-3">
                <strong>Premium (subscription):</strong> detailed analysis, unlimited scans, advanced fitness and nutrition
                programs, physical/AR games, export and sharing, full analytics.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">4. Subscription Terms</h2>
              <ul className="space-y-2 list-disc list-inside">
                <li>
                  <strong>Monthly Premium:</strong> $4.99 / month
                </li>
                <li>
                  <strong>Yearly Premium:</strong> $29.99 / year
                </li>
                <li>
                  <strong>Lifetime Premium:</strong> $49.99 one-time
                </li>
              </ul>
              <p className="mt-4">
                <strong>Auto-Renewal:</strong> Monthly and yearly subscriptions renew automatically unless cancelled at least
                24 hours before the period ends. Your Apple ID is charged within 24 hours before renewal. Manage or cancel in
                iOS Settings → [Your Name] → Subscriptions → MogME AI. Cancellation stops future charges but does not refund
                the current period. Free trials (if offered) convert to a paid subscription unless cancelled before the trial
                ends.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">5. Payment and Billing</h2>
              <p>
                All payments are processed by Apple&apos;s App Store (StoreKit). Prices are in USD and may vary by region; taxes
                may apply. We do not store payment information. Your purchase is subject to Apple&apos;s terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">6. Refund Policy</h2>
              <p>
                Refunds are handled by Apple via{' '}
                <a href={APPLE_REPORT_URL} target="_blank" rel="noopener noreferrer" className="text-yellow-400 hover:underline">
                  reportaproblem.apple.com
                </a>{' '}
                at Apple&apos;s discretion. We cannot process refunds directly. Subscriptions are not pro-rated.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">7. User Responsibilities</h2>
              <p className="mb-3">You agree to:</p>
              <ul className="space-y-2 list-disc list-inside">
                <li>Use the App for personal, non-commercial purposes only.</li>
                <li>Not reverse engineer, decompile, or modify the App.</li>
                <li>Not use the App for any illegal or unauthorized purpose.</li>
                <li>Not share your subscription or attempt to access premium features without payment.</li>
                <li>
                  Choose a username/handle that is not offensive, impersonating, infringing, or unlawful. We may reclaim,
                  change, or remove handles that violate these Terms.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">8. Online Features, Leaderboards &amp; User Conduct</h2>
              <ul className="space-y-2 list-disc list-inside">
                <li>
                  Leaderboards, AI chat, and Mog-Off are optional online features. Information you submit through them (e.g.,
                  your public handle, scores, chat messages) may be transmitted to our servers and, for AI features, a
                  third-party AI provider.
                </li>
                <li>Your public handle and scores may be displayed publicly on leaderboards.</li>
                <li>
                  You agree not to cheat, manipulate, automate, or falsify scores or rankings, and not to harass, threaten, or
                  abuse other users.
                </li>
                <li>
                  AI chat features are for entertainment and are not professional, medical, legal, or relationship advice. Do
                  not share sensitive personal information.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">9. Social Sharing</h2>
              <p>
                When you choose to share results, the App generates an image/text card on your device and passes it to the iOS
                share sheet. You are solely responsible for what you share and where. We do not post on your behalf. Shared
                content is governed by the terms of the destination platform.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">10. Mog-Off Content and Consent (18+)</h2>
              <ul className="space-y-2 list-disc list-inside">
                <li>Mog-Off is restricted to users 18+ and requires explicit image-sharing consent before the Face round.</li>
                <li>
                  Your true face photo is never uploaded. Only a numeric PSL score and a deliberately distorted, watermarked
                  outline image (generated on your device) are sent to our match server and relayed to your opponent.
                </li>
                <li>
                  You grant us a limited license to transmit, moderate, briefly store, and relay your distorted outline image,
                  trivia answers, and AI chat messages solely to operate the match. Distorted images are deleted when the round
                  resolves, the match ends, or a player disconnects.
                </li>
                <li>
                  You agree not to reconstruct, de-anonymize, capture, screenshot, redistribute, or harass others using an
                  opponent&apos;s distorted image, and not to submit any unlawful, infringing, or non-consensual content.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">11. Disclaimer of Results</h2>
              <p>
                MogME AI provides aesthetic analysis, fitness, and nutrition guidance for entertainment and informational
                purposes only. PSL scores, body scores, GPS metrics, and calorie/macro estimates are algorithmic estimates, not
                objective truth or professional advice. We do not guarantee accuracy or specific outcomes.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">12. Medical Disclaimer</h2>
              <p>
                MogME AI is NOT a medical device. Do not use it to diagnose, treat, or prevent any condition. Consult a doctor
                before starting any fitness or diet program. GPS and HealthKit tracking are informational only and not medical
                monitoring.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">13. Intellectual Property</h2>
              <p>
                MogME AI, including all code, design, and content, is owned by Ryan Joshua Fermoselle and licensed (not sold) to
                you. You retain rights to photos you capture; for standard analysis, processing is on-device and we do not claim
                rights to them.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">14. Acceptable Use</h2>
              <p>You may NOT use the App to analyze photos of other people without consent; harass, bully, or shame others; violate privacy or IP rights; engage in illegal activity; or hack, exploit, or disrupt the App or its servers.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">15. Limitation of Liability</h2>
              <p>
                To the fullest extent permitted by law, the App is provided &quot;AS IS&quot; without warranties. We are not
                liable for damages arising from use of the App, do not guarantee uninterrupted or error-free operation, and our
                maximum liability is limited to the amount you paid for your subscription.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">16. Indemnification</h2>
              <p>
                You agree to indemnify and hold harmless Ryan Joshua Fermoselle and MogME AI from claims arising from your use
                of the App, your violation of these Terms, or your violation of another party&apos;s rights.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">17. App Updates, Termination &amp; Changes</h2>
              <p>
                We may update, change, or discontinue features or the App at any time, and may terminate access for violations of
                these Terms. Termination does not entitle you to a refund for the current period.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">18. Privacy</h2>
              <p>
                Your use of the App is subject to our{' '}
                <Link href="/mog-me/privacy-policy" className="text-yellow-400 hover:underline">
                  Privacy Policy
                </Link>
                , which explains what data is processed on-device versus sent to our servers and AI provider, and your rights.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">19. Governing Law</h2>
              <p>
                These Terms are governed by the laws of the State of California, USA. Disputes will be resolved in California
                courts. Local consumer-protection laws may also apply outside the United States.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">20. Apple App Store Terms</h2>
              <p>
                You also agree to Apple&apos;s App Store Terms of Service and Media Services Terms. Apple is not a party to these
                Terms and is not responsible for the App.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-yellow-300 mb-4">21. Contact</h2>
              <ul className="space-y-2 list-disc list-inside">
                <li>
                  <strong>Email:</strong>{' '}
                  <a href={`mailto:${CONTACT_EMAIL}`} className="text-yellow-400 hover:underline">
                    {CONTACT_EMAIL}
                  </a>
                </li>
                <li>
                  <strong>Developer:</strong> Ryan Joshua Fermoselle
                </li>
              </ul>
            </section>

            <div className="bg-yellow-400/20 p-6 rounded-xl border-2 border-yellow-400/50 mt-4">
              <p className="text-green-100 font-semibold text-center">
                By using MogME AI, you acknowledge that you have read, understood, and agree to be bound by these Terms of
                Service.
              </p>
            </div>
          </div>

          <div className="text-center py-8 border-t border-yellow-400/30 mt-8">
            <p className="text-green-200 text-xl font-bold mb-2">MogME AI - Terms of Service</p>
            <p className="text-green-300 mb-4">© 2026 Ryan Joshua Fermoselle. All rights reserved.</p>
            <p className="text-green-300 mb-4">Last Updated: June 15, 2026.</p>
            <div className="flex flex-wrap items-center justify-center gap-4 text-lg mb-4">
              <Link href="/mog-me/privacy-policy" className="text-yellow-400 hover:text-yellow-300 font-semibold underline">
                Privacy Policy
              </Link>
              <span className="text-green-300">|</span>
              <Link href="/mog-me/support" className="text-yellow-400 hover:text-yellow-300 font-semibold underline">
                Support
              </Link>
            </div>
          </div>

          <div className="text-center mt-8">
            <Link
              href="/mog-me"
              className="inline-flex items-center gap-2 px-8 py-4 bg-gradient-to-r from-green-600 to-yellow-500 text-white font-bold rounded-full hover:from-green-500 hover:to-yellow-400 transition-all duration-300 transform hover:scale-105 shadow-lg"
            >
              <ArrowLeft className="w-5 h-5" />
              Back to Mog Me
            </Link>
          </div>
        </div>
      </section>

      <div className="fixed inset-0 overflow-hidden pointer-events-none" style={{ zIndex: 0 }}>
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-yellow-400/20 rounded-full blur-3xl animate-pulse" />
        <div
          className="absolute top-1/2 right-1/4 w-80 h-80 bg-green-500/20 rounded-full blur-3xl animate-pulse"
          style={{ animationDelay: '1s' }}
        />
      </div>
    </div>
  );
}
